name: deny-archives
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Fail if archives are added
        run: |
          set -euo pipefail
          if git diff --name-only origin/${{ github.base_ref }}... | grep -Ei '\.(zip|tar|tgz|gz|xz|7z)$' >/dev/null; then
            echo "::error::Compressed archives are not allowed in this repo. Use Releases or Actions artifacts."
            exit 1
          fi
